### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by drphilmarshall**
OK, I copied the basic installation that Kyle Barbary taught me at Astro Hack Week from https://github.com/kbarbary/greeter/tree/master/docs and the html builds OK, with `make html` in the `docs` directory. Next I need to see how to get it up to readthedocs, and then figure out how to build the API pages.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Alright, here we are: http://sltimer.readthedocs.io/en/issue-15-sphinx/ 

Any ideas how to get the API docs built, @heather999 ? I guess `readthedocs` is doing a `make html` - but somehow the `automodule` rst command is not doing what I had hoped it would do...

**Comment by heather999** [comment]
@drphilmarshall I don't have write access to this repository, and since there is already a PR, I'll just provide the fix here and hopefully you can add this into your conf.py file to make autodoc work.. it still may not be beautiful, but it's a start:

```
# Provide path to the python modules we want to run autodoc on
sys.path.insert(0, os.path.abspath('../python'))
# Avoid imports that may be unsatisfied when running sphinx
# See:
# http://stackoverflow.com/questions/15889621/sphinx-how-to-exclude-imports-in-automodule#15912502
autodoc_mock_imports = ["pycs", "pycs.gen.lc"]


```

**Comment by drphilmarshall** [comment]
Great, thanks @heather999  - that fixed it! Interestingly, seeing the API docs made me realize a) how badly named the modules were and b) how inhomogeneous our docstrings are! 

@chto For future reference, the one liner explanation at the top of the docstring should be of the form "Does XXX" so that in the API docs, the class methods table can be read as "<function> | | Does XXX". A number of our methods start with "To do XXX" which makes less sense when rendered by sphinx as HTML.

**Comment by drphilmarshall** [comment]
OK, docs are up at http://sltimer.readthedocs.io/en/issue-15-sphinx/

I guess we should make travis build the html, to make sure it compiles correctly at readthedocs... Or maybe there's a direct readthedocs webhook? I'll look.

**Comment by drphilmarshall** [comment]
OK: readthedocs is listed as an integration on this repo, it just doesn't report back as a "check". So I think travis needs to build the html too.

**Comment by drphilmarshall** [comment]
Attention @chto -  I renamed `SLTimer.py` to `worker.py` and `IO.py` to `reading.py`, to improve doc readability. Also, naming modules `io.py` seems to be a bad idea, it causes conflicts with some native python IO objects.

I think this is ready to go - merging!

**Comment by chto** [comment]
Got it @drphilmarshall

**Pull request merged**
